import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";

export const metadata: Metadata = {
  title: "AASTMT Room Management System",
  description:
    "Room and Lecture Hall Management System for Arab Academy for Science, Technology & Maritime Transport",
>>>>>>> 84dfc3879632e3f698f97438ea293a13c5862be3
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
    <html lang="en" className="h-full">
      <body className="min-h-full font-sans antialiased">{children}</body>
>>>>>>> 84dfc3879632e3f698f97438ea293a13c5862be3
    </html>
  );
}
